import { createTheme, rem } from "@mantine/core";
import { colors } from "./colors";

declare module "@mantine/core" {
  export interface MantineTheme {
    fontFamilySecondary: string;
  }
}

export const mantineTheme = createTheme({
  fontFamily: "Outfit, sans-serif",
  fontFamilySecondary: "Lalezar, sans-serif",
  fontSizes: {
    xs: rem(12),
    sm: rem(14),
    md: rem(16),
    lg: rem(18),
    xl: rem(20),
  },
  colors: {
    amaranthRed: [
      colors.amaranthRed[100],
      colors.amaranthRed[200],
      colors.amaranthRed[300],
      colors.amaranthRed[400],
      colors.amaranthRed[500],
      colors.amaranthRed[600],
      colors.amaranthRed[700],
      colors.amaranthRed[700],
      colors.amaranthRed[700],
      colors.amaranthRed[700],
    ],
    lightRed: [
      colors.lightRed[100],
      colors.lightRed[200],
      colors.lightRed[300],
      colors.lightRed[400],
      colors.lightRed[500],
      colors.lightRed[600],
      colors.lightRed[700],
      colors.lightRed[700],
      colors.lightRed[700],
      colors.lightRed[700],
    ],
    orange: [
      colors.orange[100],
      colors.orange[200],
      colors.orange[300],
      colors.orange[400],
      colors.orange[500],
      colors.orange[600],
      colors.orange[700],
      colors.orange[700],
      colors.orange[700],
      colors.orange[700],
    ],
    darkBrown: [
      colors.darkBrown[100],
      colors.darkBrown[200],
      colors.darkBrown[300],
      colors.darkBrown[400],
      colors.darkBrown[500],
      colors.darkBrown[600],
      colors.darkBrown[700],
      colors.darkBrown[700],
      colors.darkBrown[700],
      colors.darkBrown[700],
    ],
    gray: [
      colors.gray[100],
      colors.gray[200],
      colors.gray[300],
      colors.gray[400],
      colors.gray[500],
      colors.gray[600],
      colors.gray[700],
      colors.gray[800],
      colors.gray[900],
      colors.gray[1000],
    ],
    green: [
      colors.green[100],
      colors.green[200],
      colors.green[300],
      colors.green[400],
      colors.green[500],
      colors.green[600],
      colors.green[700],
      colors.green[800],
      colors.green[900],
      colors.green[1000],
    ],
    blue: [
      colors.blue[100],
      colors.blue[200],
      colors.blue[300],
      colors.blue[400],
      colors.blue[500],
      colors.blue[600],
      colors.blue[700],
      colors.blue[800],
      colors.blue[900],
      colors.blue[1000],
    ],
  },
  primaryColor: "blue",
  primaryShade: 5,
  defaultRadius: "md",
  breakpoints: {
    mobile: "480px",
    tablet: "768px",
    desktop: "1024px",
  },
});
